destination: _site
markdown: rdiscount
rdiscount:
  extensions: [autolink]
authors:
  pdurbin:
    display_name: Philip Durbin
  shuff:
    display_name: Steve Huff
something_to_iterate_over: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
